### ISSUE TITLE
example を文字列入力で絞り込みたい

### ISSUE THREAD

**Issue by hatz48** [tarao/apiconsole#1]
example 増えてくると探すのが大変になるので、テキストフィールドに入力したらマッチするものだけフィルタされると便利だな、と思いました。
github の assignee を選択するときのような UI を想定しています。

**Comment by hatz48** [comment]
ちょっと勘違いしていました、閉じます

**Comment by tarao** [comment]
Undocumentedな`--append`で勝手にやっている部分なのでapiconsole本体は無関係でした。
